---
- name: Leer contenido del archivo y establecer variable
  hosts: localhost
#  vars:
#    run: "pruebas.k3s"
    
  tasks:
    - name: Leer contenido del archivo nodok3_hostname.txt
      set_fact:
        nodo_hostname: "{{ lookup('file', '/pruebas/nodok3_hostname.txt') }}"
    - name: Mostrar valor de nodok3_hostnametxt para verificación
      debug:
        var: nodo_hostname

# En esta seccion comparo las salidas si la variable run declarada en ambos playbook (playbook1.yaml y playbook2.yaml) es igual a la variable leida del archivo nodok3_hostname.txt,
# Entonces se ejecuta el playbook importadode lo contrario la tarea es skipping.

- import_playbook: playbook1.yaml
  when: run == "Disabled" and nodo_hostname == "Disabled"
- import_playbook: playbook2.yaml
  when: run == "pruebas.k3s" and nodo_hostname == "pruebas.k3s"
